### ISSUE TITLE
仓库克隆到本地运行报错

### ISSUE THREAD

**Issue by zhaozhe0831** [AngusFu/vuepress-plugin-playground#3]
`npm run start`

![image](https://user-images.githubusercontent.com/12945873/93412662-2a9c6500-f8d0-11ea-8285-7df048829d0a.png)

![image](https://user-images.githubusercontent.com/12945873/93412740-54ee2280-f8d0-11ea-9831-13473e21a9a6.png)

估计是这里的解析有问题

**Comment by AngusFu** [comment]
建议使用 https://github.com/BuptStEve/vuepress-plugin-demo-code

可能过阵子我时间充裕了，还会继续维护起来。
